<?php include "notLoggedInHeader.phtml" ?>
<!---------- Body starts --------------->
<head>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript">

        function checkAvailability() {
            $.ajax({
                type: "POST",
                url: "/account/jquery/",
                dataType: "json",
                data:'username='+$("#username").val(),
                success: function(data) {
                    console.log(data);
                    if (data == 1){
                        $("#user-availability-status").addClass("userBusy");
                       $("#user-availability-status").removeClass("userFree");

                    } else {
                        $("#user-availability-status").addClass("userFree");

                        $("#user-availability-status").removeClass("userBusy");
                        }
                }
             });
        }
    </script>
    <style type="text/css">
        .login-form {
            width: 440px;
            margin: 50px auto;
        }
        .login-form form {
            margin-bottom: 15px;
            background: #f7f7f7;
            box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
            padding: 30px;
        }
        .login-form h2 {
            margin: 0 0 15px;
        }
        .btn {
            font-size: 15px;
            font-weight: bold;
        }
    </style>

</head>
<body>

<div class="login-form">
<form action="" method="POST">
    <div class="container">
        <h1>Register</h1>
        <p>Please fill in this form to create an account.</p>
        <hr>


        <label for="name"><b>Name</b></label>
        <input type="text" class="form-control" placeholder="Enter Name" name="name" required>
        <br>

        <div id="frmCheckUsername">
            <label for="username"><b>Username</b></label>
            <input type="text" class="form-control" id="username" placeholder="Enter Username" name="username" required  onkeyup="checkAvailability()">
            <span id="user-availability-status" class="userFree userBusy">
              <b>available</b>
          	</span>
        </div>
        <br>

        <label for="email"><b>Email</b></label>
        <input type="text" class="form-control" placeholder="Enter Email" name="email" required>
        <br>

        <label for="psw"><b>Password</b></label>
        <input type="password" class="form-control" placeholder="Enter Password" name="psw" required>
        <br>

        <label for="psw-repeat"><b>Repeat Password</b></label>
        <input type="password" class="form-control" placeholder="Repeat Password" name="psw-repeat" required>
        <hr>

        <div class="text-center ">
            <?php if (!empty($missing)) {echo $missing . '<br>'; } ?>
        </div>
        <button type="submit" class="btn btn-dark btn-block">Register</button>
    </div>


</form>
    </div>

</body>
<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>
