<?php include "header.phtml" ?>
<!---------- Body starts --------------->
<head>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript">

        function checkAvailability() {
            $.ajax({
                type: "POST",
                url: "/account/jquery/",
                dataType: "json",
                data:'username='+$("#username").val(),
                success: function(data) {
                    console.log(data);
                    if (data == 1){
                        $("#user-availability-status").addClass("userBusy");
                       $("#user-availability-status").removeClass("userFree");

                    } else {
                        $("#user-availability-status").addClass("userFree");

                        $("#user-availability-status").removeClass("userBusy");
                        }
                }
             });
        }
    </script>

</head>
<body>

<?php if (!empty($missing)) {echo $missing . '<br>'; } ?>

<form action="" method="POST">
    <div class="container">
        <h1>Register</h1>
        <p>Please fill in this form to create an account.</p>
        <hr>


        <label for="name"><b>Name</b></label>
        <input type="text" placeholder="Enter Name" name="name" required>
        <br>

        <div id="frmCheckUsername">
            <label for="username"><b>Username</b></label>
            <input type="text" id="username" placeholder="Enter Username" name="username" required  onkeyup="checkAvailability()">
            <span id="user-availability-status" class="userFree userBusy">
              <b>available</b>
          	</span>
        </div>
        <br>

        <label for="email"><b>Email</b></label>
        <input type="text" placeholder="Enter Email" name="email" required>
        <br>

        <label for="psw"><b>Password</b></label>
        <input type="password" placeholder="Enter Password" name="psw" required>
        <br>

        <label for="psw-repeat"><b>Repeat Password</b></label>
        <input type="password" placeholder="Repeat Password" name="psw-repeat" required>
        <hr>

        <button type="submit" class="registerbtn">Register</button>
    </div>


</form>

</body>
<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>
